clc;
clear;
I=imread('soru2-1.png');
figure,imshow(I),title('Asıl Resim');
R=I(:,:,1);
G=I(:,:,2);
B=I(:,:,3);
%figure,imshow(R),title('R');
%figure,imshow(G),title('G');
%figure,imshow(B),title('B');
R2=(R>50);
G2=(G>50);
B2=(B>50);
%figure,imshow(R2),title('R2');
%figure,imshow(G2),title('G2');
%figure,imshow(B2),title('B2');
R3=(R2>G2);
R3=(R3>B2);
se=strel('disk',2,0);
R3=imerode(R3,se);
%figure,imshow(R3),title('R3 Erezyonlu');
hassaslik=0.65;
[ortaNokta,cap] = imfindcircles(R3,[6 300],'Sensitivity',hassaslik);
daireSayisi=length(ortaNokta);
yazi1=['Daire Saıyısı: ' num2str(daireSayisi)];
yazi2=['Bazen büyüklüğünden dolayı kırmızı daire olduğu halde bulamıyor (örnek resim: soru2-3.png). Bunu gidermek için 22. satırdaki,']; 
yazi3=['< imfindcircles > fonksiyonunda <Sensitivity>''nin sağındaki ' num2str(hassaslik) ' olan değeri yükseltmeniz gerekiyor.'];
R3=uint8(R3)*255;
[en,boy]=size(R3);
R3 = insertText(R3,[1 1],yazi1,'FontSize',36,'BoxColor','red','BoxOpacity',0.4,'TextColor','white');
R3 = insertText(R3,[1 en-91],yazi2,'FontSize',23,'BoxColor','white','BoxOpacity',0.6,'TextColor','black');
R3 = insertText(R3,[1 en-50],yazi3,'FontSize',23,'BoxColor','white','BoxOpacity',0.6,'TextColor','black');
figure,imshow(R3),title('Kırmızı Daireler');
viscircles(ortaNokta, cap,'EdgeColor','r','LineStyle','--');